---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tkm-csi-node-sa
  namespace: tkm-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tkm-csi-node-role
  namespace: tkm-system
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tkm-csi-node-binding
subjects:
  - kind: ServiceAccount
    name: tkm-csi-node-sa
    namespace: tkm-system
roleRef:
  kind: ClusterRole
  name: tkm-csi-node-role
  apiGroup: rbac.authorization.k8s.io
