---
apiVersion: tkm.io/v1alpha1
kind: TritonKernelCacheCluster
metadata:
  name: flash-attention-rocm
spec:
  cacheImage: quay.io/tkm/vector-add-cache:rocm
  validateSignature: false
---
kind: Pod
apiVersion: v1
metadata:
  name: tkm-csi-test
  namespace: tkm-system
spec:
  tolerations:
    - key: gpu
      operator: Equal
      effect: NoSchedule
      value: "true"
  nodeSelector:
    tkm-test-node: "true"
  containers:
  - name: alpine
    image: quay.io/fedora/fedora-minimal
    imagePullPolicy: "IfNotPresent"
    command: ["sleep", "365d"]
    volumeMounts:
    - name: kernel-volume
      mountPath: "/cache"
  volumes:
  - name: kernel-volume
    csi:
      driver: csi.tkm.io
      volumeAttributes:
        csi.tkm.io/tritonKernelCache: flash-attention-rocm
